typography_spectrum: 0.8969271131791174
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7063522327225655
  lightness: 0.2850446794182062
  saturation: 0.6265111325774342
  rhythmicContrast: 0.30804408341646194
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5791546299587935
analytics:
  google: null
  facebook: null
  twitter: null
name: BakersBrigade
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: A Big Cake
purpose: []
